### ISSUE TITLE
Add All of The HackerRank Interview Preparation Kit Sorting Solution

### ISSUE THREAD

**Issue by FreshlyBuilt** [FreshlyBuilt/Competitive-Programming#18]
Students are invited to attach solutions to all questions under the Sorting Topic. You can submit your solution in any of the programming languages but it should contain solutions to all questions, not half or double question.

**Comment by egurnick** [comment]
Hi, can you please assign this to me? I will contribute solutions in Python

**Comment by vishal2612200** [comment]
Fest already ended long ago.
